<?php
	  set_time_limit(0);
	  //error_reporting (E_ALL ^ E_NOTICE);
     // echo(date('l jS \of F Y h:i:s A - '));
      require_once("CRM_Conexion.php");
	$num=preg_replace ("[\n|\r|\n\r]","",fgets(fopen("vicidial", "r")));
	$y=0;
       for($i=1;$i<$num;$i++){
           $ConexionCRM=new Conexion($i);
           $ConexionCRM->Open();
	    $result=mysql_query("optimize table tbl_Calificacion_Registro",$ConexionCRM->cn);
		$resp=mysql_fetch_assoc($result);
		echo($resp["Table"]." ");
		echo($resp["Op"]." ");
		echo($resp["Msg_type"]." ");
		echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table tbl_Campana",$ConexionCRM->cn);
		$resp=mysql_fetch_assoc($result);
		echo($resp["Table"]." ");
		echo($resp["Op"]." ");
		echo($resp["Msg_type"]." ");
		echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table tbl_Campana_Campo",$ConexionCRM->cn);
		$resp=mysql_fetch_assoc($result);
		echo($resp["Table"]." ");
		echo($resp["Op"]." ");
		echo($resp["Msg_type"]." ");
		echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table tbl_Campana_Campo_Registro",$ConexionCRM->cn);
		$resp=mysql_fetch_assoc($result);
		echo($resp["Table"]." ");
		echo($resp["Op"]." ");
		echo($resp["Msg_type"]." ");
		echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table tbl_Campana_Colores",$ConexionCRM->cn);
		$resp=mysql_fetch_assoc($result);
		echo($resp["Table"]." ");
		echo($resp["Op"]." ");
		echo($resp["Msg_type"]." ");
		echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table tbl_Pago_Registro",$ConexionCRM->cn);
		$resp=mysql_fetch_assoc($result);
		echo($resp["Table"]." ");
		echo($resp["Op"]." ");
		echo($resp["Msg_type"]." ");
		echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table tbl_Registro",$ConexionCRM->cn);
		$resp=mysql_fetch_assoc($result);
		echo($resp["Table"]." ");
		echo($resp["Op"]." ");
		echo($resp["Msg_type"]." ");
		echo($resp["Msg_text"]."<BR>");
    	 }  
	 $ConexionCRM=new Conexion($num);
	 $ConexionCRM->Open();
	    $result=mysql_query("optimize table call_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table call_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table callcard_accounts",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table callcard_accounts_details",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table callcard_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table conferences",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table contact_information",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table dialable_inventory_snapshots",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table groups_alias",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table inbound_email_attachments",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table inbound_numbers",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table live_channels",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table live_inbound",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table live_inbound_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table live_sip_channels",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table nanpa_prefix_exchanges_fast",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table nanpa_prefix_exchanges_master",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table nanpa_wired_to_wireless",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table nanpa_wireless_to_wired",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table park_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table parked_channels",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table phone_favorites",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table phones",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table phones_alias",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table recording_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table server_performance",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table server_updater",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table servers",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table system_settings",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table twoday_call_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table twoday_recording_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table twoday_vicidial_agent_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table twoday_vicidial_closer_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table twoday_vicidial_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table twoday_vicidial_xfer_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table user_call_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_admin_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_agent_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_agent_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_agent_skip_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_agent_sph",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_api_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_auto_calls",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_call_menu",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_call_menu_options",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_call_notes",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_call_notes_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_call_time_holidays",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_call_times",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_callbacks",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaign_agents",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaign_cid_areacodes",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaign_dnc",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaign_hotkeys",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaign_server_stats",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaign_stats",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaign_stats_debug",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaign_statuses",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaigns",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_campaigns_list_mix",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_carrier_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_carrier_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_closer_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_closer_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_comments",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_conf_templates",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_conferences",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_configuration",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_cpd_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_custom_cid",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_custom_leadloader_templates",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_daily_max_stats",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_daily_ra_stats",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_dial_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_dial_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_did_agent_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_did_agent_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_did_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_did_ra_extensions",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_dnc",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_drop_rate_groups",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_email_accounts",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_email_list",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_email_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_extension_groups",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_filter_phone_groups",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_filter_phone_numbers",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_grab_call_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_hopper",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_inbound_dids",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_inbound_group_agents",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_inbound_groups",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_ivr",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_lead_filters",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_lead_recycle",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_lead_search_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_lead_search_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_list",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_list_alt_phones",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_list_pins",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_list_update_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_lists",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_lists_custom",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_lists_fields",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_live_agents",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_live_inbound_agents",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_log_extended",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_log_extended_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_log_noanswer",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_log_noanswer_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_manager",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_manual_dial_queue",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_monitor_calls",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_monitor_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_music_on_hold",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_music_on_hold_files",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_nanpa_filter_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_nanpa_prefix_codes",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_outbound_ivr_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_outbound_ivr_log_archive",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_override_ids",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_pause_codes",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_phone_codes",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_postal_codes",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_process_trigger_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_process_triggers",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_qc_agent_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_qc_codes",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_remote_agent_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_remote_agents",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_report_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_screen_labels",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_scripts",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_server_carriers",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_server_trunks",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_session_data",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_shifts",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_state_call_times",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_stations",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_status_categories",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_statuses",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_territories",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_timeclock_audit_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_timeclock_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_timeclock_status",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_tts_prompts",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_url_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_user_closer_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_user_groups",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_user_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_user_territories",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_user_territory_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_users",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_voicemail",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_xfer_log",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_xfer_presets",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vicidial_xfer_stats",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vtiger_rank_data",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vtiger_rank_parameters",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vtiger_vicidial_roles",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table web_client_sessions",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $ConexionCRM=new Conexion($num+1);
$ConexionCRM->Open();
	    $result=mysql_query("optimize table cat_estados",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table cat_sucursales",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table cat_tipo_usuario",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table cdr",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table cdr_copy",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table conexion",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table config",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table funcionalidades",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table grupos",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table hangupcauses",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table sessions",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table usuarios",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vcdr",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    $result=mysql_query("optimize table vusuarios",$ConexionCRM->cn);
 $resp=mysql_fetch_assoc($result);
 echo($resp["Table"]." ");
 echo($resp["Op"]." "); 
 echo($resp["Msg_type"]." ");
 echo($resp["Msg_text"]."<BR>");
	    header("Location: mantenimiento.php?tipo=".$_GET["tipo"]."&y=1");
?>